#ifndef C16_PIPELINE_HPP
#define C16_PIPELINE_HPP

// Driving the compiler: read a source buffer, run every stage on whichever
// backend was asked for, and hand back either cpu16 assembly text or cpu16
// machine words.
//
// The two output paths share everything up to the last stage:
//
//   text    formats one assembly line per lowered item.  The existing asm16
//           assembles that output unmodified, which is the point - the
//           compiler is not allowed a private encoding of anything.
//   binary  hands each lowered item to the assembler's own encoder and gets
//           machine words, skipping the text and the lexing of it entirely.
//
// Both must produce the same machine code, and tests/run_c16_test.sh checks
// that per program rather than trusting it.

#include "asm_pipeline.hpp"
#include "c16_compiler.hpp"
#include "c16_hip.hpp"
#include "c16_kernel.hpp"

#include <atomic>
#include <cstring>
#include <string>
#include <vector>

inline constexpr const char* c16_text_header =
    "# cpu16 assembly generated by c16, the small C like compiler.\n"
    "# Assemble it with:  asm16 --hex --sep_with_line\n";

// ------------------------------------------------------------- scheduling

// Functions differ wildly in size, so handing each thread a fixed contiguous
// range of them - which is what asm_parallel_for does, and what is right for
// the assembler's uniform per line work - leaves cores idle.  Lowering takes
// its functions off a shared counter instead.
template <class Fn>
inline void c16_parallel_dynamic(size_t n, unsigned threads, Fn fn) {
    if (threads <= 1 || n < 2) {
        for (size_t i = 0; i < n; i++) {
            fn(i);
        }
        return;
    }
    std::atomic<size_t> next{0};
    unsigned used = static_cast<unsigned>(std::min<size_t>(threads, n));
    std::vector<std::thread> pool;
    pool.reserve(used - 1);
    auto worker = [&] {
        for (;;) {
            size_t i = next.fetch_add(1, std::memory_order_relaxed);
            if (i >= n) {
                return;
            }
            fn(i);
        }
    };
    for (unsigned t = 1; t < used; t++) {
        pool.emplace_back(worker);
    }
    worker();
    for (auto& t : pool) {
        t.join();
    }
}

// An exclusive prefix sum, chunked the same way the assembler's address scan
// is: every thread totals its own slice, the slice totals are added up in
// order, and every thread then fills its slice from its own base.  Returns
// the total.
inline uint64_t c16_exclusive_scan(const uint32_t* in, uint32_t* out, size_t n,
                                   unsigned threads) {
    if (n == 0) {
        return 0;
    }
    asm_chunking cut(n, threads);
    std::vector<uint64_t> base(cut.count + 1, 0);
    asm_parallel_for(cut.count, cut.threads, [&](size_t begin, size_t end) {
        for (size_t c = begin; c < end; c++) {
            uint64_t sum = 0;
            for (size_t i = cut.begin(c); i < cut.end(c, n); i++) {
                sum += in[i];
            }
            base[c + 1] = sum;
        }
    });
    for (size_t c = 0; c < cut.count; c++) {
        base[c + 1] += base[c];
    }
    asm_parallel_for(cut.count, cut.threads, [&](size_t begin, size_t end) {
        for (size_t c = begin; c < end; c++) {
            uint64_t running = base[c];
            for (size_t i = cut.begin(c); i < cut.end(c, n); i++) {
                out[i] = static_cast<uint32_t>(running);
                running += in[i];
            }
        }
    });
    return base[cut.count];
}

// ------------------------------------------------------------- front end

inline std::string_view c16_token_text(const std::vector<char>& source, const c16_token& t) {
    return std::string_view(source.data() + t.off, t.len);
}

inline void c16_set_error(c16_error& e, const c16_token& t, std::string message) {
    if (e.failed) {
        return;
    }
    e.failed = true;
    e.line = t.line;
    e.message = std::move(message);
}

// Lex the whole source.  Per line, so parallel, in the two passes any
// compaction needs: count the tokens on every line, prefix sum, fill.
inline bool c16_lex(const std::vector<char>& source, const asm_array<asm_span>& lines,
                    const c16_options& opt, unsigned threads,
                    std::vector<c16_token>& tokens, std::string* err) {
    size_t n = lines.size();
    std::vector<uint32_t> counts(n + 1, 0);
    std::vector<uint32_t> offsets(n + 1, 0);
    const char* base = source.data();
    const asm_span* line = lines.data();

    if (opt.backend == c16_backend::hip) {
        if (n != 0 && !c16_hip_lex_count(base, source.size(), line, n, counts.data(), err)) {
            return false;
        }
    }
    else {
        uint32_t* count = counts.data();
        asm_parallel_for(n, threads, [=](size_t begin, size_t end) {
            for (size_t i = begin; i < end; i++) {
                count[i] = c16_lex_line(base, line[i], static_cast<uint32_t>(i) + 1, nullptr);
            }
        });
    }

    uint64_t total = c16_exclusive_scan(counts.data(), offsets.data(), n, threads);
    tokens.resize(total + 1);

    if (opt.backend == c16_backend::hip) {
        if (n != 0 && !c16_hip_lex_fill(base, source.size(), line, n, offsets.data(),
                                        tokens.data(), total, err)) {
            return false;
        }
    }
    else {
        c16_token* out = tokens.data();
        const uint32_t* at = offsets.data();
        asm_parallel_for(n, threads, [=](size_t begin, size_t end) {
            for (size_t i = begin; i < end; i++) {
                c16_lex_line(base, line[i], static_cast<uint32_t>(i) + 1, out + at[i]);
            }
        });
    }

    // One sentinel, so that every lookahead in the parser is in bounds.
    c16_token& sentinel = tokens[total];
    sentinel.off = 0;
    sentinel.len = 0;
    sentinel.line = n == 0 ? 1 : static_cast<uint32_t>(n);
    sentinel.value = 0;
    sentinel.kind = C16_TOK_END;
    sentinel.pad = 0;
    return true;
}

// Split the token stream into globals and functions.
//
// This is the ordered part of the front end and there is no getting around
// it: which "{" closes which "}" is a running count, and a function's extent
// is not knowable from any one token.  It is one linear pass that reads a
// token kind and a counter, so it is memory bound rather than expensive, and
// the benchmark prints what it costs.
inline bool c16_split(const std::vector<char>& source, const std::vector<c16_token>& tokens,
                      std::vector<c16_function>& functions,
                      std::vector<c16_global>& globals, c16_error& error) {
    size_t n = tokens.size() - 1;   // the sentinel is not a real token
    auto kind = [&](size_t i) -> uint16_t {
        return i < n ? tokens[i].kind : static_cast<uint16_t>(C16_TOK_END);
    };
    size_t i = 0;
    while (i < n) {
        if (kind(i) != C16_TOK_INT) {
            c16_set_error(error, tokens[i],
                          std::format("expected 'int' at the top level but found '{}'",
                                      std::string(c16_token_text(source, tokens[i]))));
            return false;
        }
        if (kind(i + 1) != C16_TOK_IDENT) {
            c16_set_error(error, tokens[std::min(i + 1, n)], "expected a name after 'int'");
            return false;
        }
        std::string_view name = c16_token_text(source, tokens[i + 1]);

        if (kind(i + 2) != C16_TOK_LPAREN) {
            c16_global g;
            g.name = name;
            size_t j = i + 2;
            int32_t init = 0;
            if (kind(j) == C16_TOK_ASSIGN) {
                j++;
                int32_t sign = 1;
                if (kind(j) == C16_TOK_MINUS) {
                    sign = -1;
                    j++;
                }
                if (kind(j) != C16_TOK_NUMBER) {
                    c16_set_error(error, tokens[std::min(j, n)],
                                  "a global's initialiser has to be an integer literal");
                    return false;
                }
                init = sign * tokens[j].value;
                if (init < -128 || init > 255) {
                    c16_set_error(error, tokens[j],
                                  std::format("the literal {} does not fit in cpu16's "
                                              "8 bit data", init));
                    return false;
                }
                j++;
            }
            if (kind(j) != C16_TOK_SEMI) {
                c16_set_error(error, tokens[std::min(j, n)], "expected ';'");
                return false;
            }
            g.init = init & 0xff;
            globals.push_back(g);
            i = j + 1;
            continue;
        }

        c16_function f;
        f.name = name;
        f.name_token = static_cast<uint32_t>(i + 1);
        size_t j = i + 3;
        if (kind(j) == C16_TOK_RPAREN) {
            j++;
        }
        else {
            for (;;) {
                if (kind(j) != C16_TOK_INT || kind(j + 1) != C16_TOK_IDENT) {
                    c16_set_error(error, tokens[std::min(j, n)],
                                  "a parameter has to be written 'int <name>'");
                    return false;
                }
                if (f.nparams >= C16_MAX_PARAMS) {
                    c16_set_error(error, tokens[j],
                                  std::format("more than {} parameters", C16_MAX_PARAMS));
                    return false;
                }
                f.param_token[f.nparams++] = static_cast<uint32_t>(j + 1);
                j += 2;
                if (kind(j) == C16_TOK_COMMA) {
                    j++;
                    continue;
                }
                if (kind(j) == C16_TOK_RPAREN) {
                    j++;
                    break;
                }
                c16_set_error(error, tokens[std::min(j, n)], "expected ',' or ')'");
                return false;
            }
        }
        if (kind(j) != C16_TOK_LBRACE) {
            c16_set_error(error, tokens[std::min(j, n)], "expected '{' to open the body");
            return false;
        }
        f.body_begin = static_cast<uint32_t>(j);
        uint32_t depth = 0;
        size_t k = j;
        for (; k < n; k++) {
            if (tokens[k].kind == C16_TOK_LBRACE) {
                depth++;
            }
            else if (tokens[k].kind == C16_TOK_RBRACE) {
                depth--;
                if (depth == 0) {
                    break;
                }
            }
        }
        if (k >= n) {
            c16_set_error(error, tokens[j],
                          std::format("'{}' is missing a closing '}}'", std::string(name)));
            return false;
        }
        f.body_end = static_cast<uint32_t>(k);
        functions.push_back(f);
        i = k + 1;
    }
    return true;
}

// ------------------------------------------------------------- the driver

struct c16_program {
    std::vector<c16_token> tokens;
    std::vector<c16_function> functions;
    std::vector<c16_global> globals;
    std::unordered_map<std::string_view, uint32_t> function_index;
    std::unordered_map<std::string_view, uint32_t> global_index;
};

// Every function's calls are known once it has been lowered, so this is where
// recursion is caught.  It has to be caught: frames are allocated once per
// function, not once per call, so a recursive program would quietly overwrite
// its own locals.
inline bool c16_check_recursion(const std::vector<c16_function>& functions,
                                const std::vector<c16_lowered>& lowered,
                                const std::vector<c16_token>& tokens,
                                c16_error& error) {
    enum : uint8_t { white = 0, grey = 1, black = 2 };
    std::vector<uint8_t> colour(functions.size(), white);
    std::vector<std::pair<uint32_t, size_t>> stack;
    for (uint32_t root = 0; root < functions.size(); root++) {
        if (colour[root] != white) {
            continue;
        }
        stack.push_back({root, 0});
        colour[root] = grey;
        while (!stack.empty()) {
            auto& [f, next] = stack.back();
            const std::vector<uint32_t>& calls = lowered[f].calls;
            if (next >= calls.size()) {
                colour[f] = black;
                stack.pop_back();
                continue;
            }
            uint32_t callee = calls[next++];
            if (colour[callee] == grey) {
                c16_set_error(error, tokens[functions[callee].name_token],
                              std::format("'{}' takes part in a cycle of calls, and c16 "
                                          "gives every function one fixed frame, so "
                                          "recursion is not supported",
                                          std::string(functions[callee].name)));
                return false;
            }
            if (colour[callee] == white) {
                colour[callee] = grey;
                stack.push_back({callee, 0});
            }
        }
    }
    return true;
}

// ------------------------------------------------------------- emit

inline bool c16_emit_text(const asm_array<c16_item>& items, const c16_options& opt,
                          unsigned threads, asm_array<uint8_t>& out, std::string* err) {
    size_t n = items.size();
    std::vector<uint32_t> lengths(n);
    std::vector<uint32_t> offsets(n);
    const c16_item* it = items.data();

    if (opt.backend == c16_backend::hip) {
        if (n != 0 && !c16_hip_text_lengths(it, n, lengths.data(), err)) {
            return false;
        }
    }
    else {
        uint32_t* length = lengths.data();
        asm_parallel_for(n, threads, [=](size_t begin, size_t end) {
            for (size_t i = begin; i < end; i++) {
                length[i] = c16_text_length(it[i]);
            }
        });
    }

    uint64_t total = c16_exclusive_scan(lengths.data(), offsets.data(), n, threads);
    size_t header = std::strlen(c16_text_header);
    out.reset(header + total);
    std::memcpy(out.data(), c16_text_header, header);

    if (opt.backend == c16_backend::hip) {
        if (n != 0 && !c16_hip_text_write(it, n, offsets.data(), out.data() + header,
                                          total, err)) {
            return false;
        }
        return true;
    }
    uint8_t* bytes = out.data() + header;
    const uint32_t* at = offsets.data();
    asm_parallel_for(n, threads, [=](size_t begin, size_t end) {
        for (size_t i = begin; i < end; i++) {
            c16_text_write(it[i], reinterpret_cast<char*>(bytes) + at[i]);
        }
    });
    return true;
}

inline bool c16_emit_binary_all(const asm_array<c16_item>& items, size_t words,
                                const c16_options& opt, unsigned threads,
                                asm_array<uint8_t>& out, std::string* err) {
    asm_format fmt{static_cast<uint8_t>(opt.hex ? 1 : 0),
                   static_cast<uint8_t>(asm_cpu16::word_bytes),
                   opt.sep_with_line ? '\n' : ',', 0};
    out.reset(words * asm_bytes_per_word(fmt));
    size_t n = items.size();
    const c16_item* it = items.data();
    if (opt.backend == c16_backend::hip) {
        return n == 0 || out.size() == 0 ||
               c16_hip_binary(it, n, out.data(), out.size(), fmt, err);
    }
    uint8_t* bytes = out.data();
    asm_parallel_for(n, threads, [=](size_t begin, size_t end) {
        for (size_t i = begin; i < end; i++) {
            c16_emit_binary(it[i], bytes, fmt);
        }
    });
    return true;
}

// ------------------------------------------------------------- compile

inline c16_result c16_compile(const std::vector<char>& source, const c16_options& opt) {
    c16_result result;
    result.stats.input_bytes = source.size();
    unsigned threads = opt.backend == c16_backend::serial ? 1u : opt.threads;
    result.stats.threads = threads;

    auto fail = [&](const c16_error& e) {
        result.error = e;
        result.ok = false;
        return std::move(result);
    };
    auto fail_text = [&](uint32_t line, std::string message) {
        c16_error e;
        e.failed = true;
        e.line = line;
        e.message = std::move(message);
        return fail(e);
    };

    // ---- lex
    double t0 = asm_now();
    asm_array<asm_span> lines = asm_split_lines(source, threads);
    result.stats.lines = lines.size();
    c16_program program;
    std::string err;
    if (!c16_lex(source, lines, opt, threads, program.tokens, &err)) {
        return fail_text(0, err);
    }
    result.stats.tokens = program.tokens.size() - 1;
    double t1 = asm_now();

    // ---- split
    c16_error error;
    if (!c16_split(source, program.tokens, program.functions, program.globals, error)) {
        return fail(error);
    }
    double t2 = asm_now();

    // ---- names, frames
    if (program.functions.empty()) {
        return fail_text(0, "the program has no functions, and needs a 'main'");
    }
    size_t main_at = program.functions.size();
    for (size_t i = 0; i < program.functions.size(); i++) {
        if (program.functions[i].name == "main") {
            main_at = i;
            break;
        }
    }
    if (main_at == program.functions.size()) {
        return fail_text(0, "the program has no 'main'");
    }
    if (program.functions[main_at].nparams != 0) {
        return fail_text(program.tokens[program.functions[main_at].name_token].line,
                         "'main' takes no arguments");
    }
    // main has to sit at address 0, because that is where the CPU starts.
    std::swap(program.functions[0], program.functions[main_at]);

    for (uint32_t i = 0; i < program.functions.size(); i++) {
        const c16_function& f = program.functions[i];
        if (f.name == "peek" || f.name == "poke" || f.name == "out") {
            return fail_text(program.tokens[f.name_token].line,
                             std::format("'{}' is a builtin and cannot be redefined",
                                         std::string(f.name)));
        }
        if (!program.function_index.emplace(f.name, i).second) {
            return fail_text(program.tokens[f.name_token].line,
                             std::format("'{}' is defined twice", std::string(f.name)));
        }
    }

    uint32_t address = C16_VAR_BASE;
    for (uint32_t i = 0; i < program.globals.size(); i++) {
        program.globals[i].address = address++;
        if (!program.global_index.emplace(program.globals[i].name, i).second) {
            return fail_text(0, std::format("'{}' is defined twice",
                                            std::string(program.globals[i].name)));
        }
    }

    // How big a frame each function needs.  Locals are exactly the "int"
    // declarations in the body, which can be counted without parsing, so
    // frames can be handed out before lowering starts and lowering can then
    // run on every function at once.
    c16_parallel_dynamic(program.functions.size(), threads, [&](size_t i) {
        c16_function& f = program.functions[i];
        uint32_t locals = 0;
        for (uint32_t k = f.body_begin; k < f.body_end; k++) {
            if (program.tokens[k].kind == C16_TOK_INT) {
                locals++;
            }
        }
        f.nlocals = locals;
        f.frame_size = 1 + f.nparams + locals;
    });
    for (c16_function& f : program.functions) {
        f.frame = address;
        address += f.frame_size;
    }
    if (!opt.relaxed_limits && address > C16_VAR_BASE + C16_VAR_SIZE) {
        return fail_text(0, std::format("the program needs {} bytes of variables and "
                                        "frames, and cpu16 has room for {}",
                                        address - C16_VAR_BASE, C16_VAR_SIZE));
    }
    double t3 = asm_now();

    // ---- lower, one function at a time but every function at once
    size_t nfunctions = program.functions.size();
    result.stats.functions = nfunctions;
    std::vector<c16_lowered> lowered(nfunctions);
    c16_parallel_dynamic(nfunctions, threads, [&](size_t i) {
        c16_lowerer lower(source, program.tokens, program.functions, program.function_index,
                          program.globals, program.global_index, static_cast<uint32_t>(i));
        lowered[i] = lower.run();
    });
    // Report the failure that is earliest in the source, so that the message
    // does not depend on which thread happened to finish first.
    const c16_lowered* first_failure = nullptr;
    for (const c16_lowered& l : lowered) {
        if (l.error.failed && (first_failure == nullptr ||
                               l.error.token < first_failure->error.token)) {
            first_failure = &l;
        }
    }
    if (first_failure != nullptr) {
        return fail(first_failure->error);
    }
    if (!c16_check_recursion(program.functions, lowered, program.tokens, error)) {
        return fail(error);
    }
    // Every out() slot any function writes has to be copied back by main's
    // epilogue, and only main knows where the epilogue is, so the union is
    // taken here and the epilogue rewritten with it.
    uint32_t out_mask = 0;
    for (const c16_lowered& l : lowered) {
        out_mask |= l.out_mask;
    }
    if (out_mask != lowered[0].out_mask) {
        c16_lowerer relower(source, program.tokens, program.functions, program.function_index,
                            program.globals, program.global_index, 0);
        lowered[0] = relower.run(out_mask);
    }
    double t4 = asm_now();

    // ---- layout: a prefix sum over functions, then a parallel fill
    std::vector<uint64_t> item_base(nfunctions + 1, 0);
    std::vector<uint32_t> word_base(nfunctions + 1, 0);
    std::vector<uint32_t> label_base(nfunctions + 1, 0);
    for (size_t i = 0; i < nfunctions; i++) {
        item_base[i + 1] = item_base[i] + lowered[i].items.size();
        word_base[i + 1] = word_base[i] + lowered[i].words;
        label_base[i + 1] = label_base[i] + lowered[i].nlabels;
    }
    result.stats.items = item_base[nfunctions];
    result.stats.words = word_base[nfunctions];
    if (!opt.relaxed_limits && word_base[nfunctions] > C16_PROGRAM_WORDS) {
        return fail_text(0, std::format("the program is {} instruction words and cpu16 "
                                        "has room for {}",
                                        word_base[nfunctions], C16_PROGRAM_WORDS));
    }

    asm_array<c16_item> items;
    items.reset(item_base[nfunctions]);
    std::vector<uint32_t> label_address(label_base[nfunctions], 0);
    c16_parallel_dynamic(nfunctions, threads, [&](size_t f) {
        uint32_t at = word_base[f];
        c16_item* dst = items.data() + item_base[f];
        const std::vector<c16_item>& src = lowered[f].items;
        for (size_t k = 0; k < src.size(); k++) {
            c16_item copy = src[k];
            copy.address = at;
            if (copy.kind == C16_ITEM_LABEL) {
                copy.label = label_base[f] + copy.label;
                label_address[copy.label] = at;
            }
            else if (copy.kind == C16_ITEM_LA) {
                copy.label = (copy.label & C16_FUNCTION_TAG) != 0
                             ? label_base[copy.label & ~C16_FUNCTION_TAG] + C16_ENTRY_LABEL
                             : label_base[f] + copy.label;
            }
            at += c16_item_words(copy);
            dst[k] = copy;
        }
    });
    double t5 = asm_now();

    // ---- resolve: every "la" learns its label's address
    {
        c16_item* it = items.data();
        const uint32_t* label_at = label_address.data();
        asm_parallel_for(items.size(), threads, [=](size_t begin, size_t end) {
            for (size_t i = begin; i < end; i++) {
                if (it[i].kind == C16_ITEM_LA) {
                    it[i].target = static_cast<int32_t>(label_at[it[i].label]);
                }
            }
        });
    }
    double t6 = asm_now();

    // ---- emit
    bool emitted = opt.text
                   ? c16_emit_text(items, opt, threads, result.output, &err)
                   : c16_emit_binary_all(items, word_base[nfunctions], opt, threads,
                                         result.output, &err);
    if (!emitted) {
        result.output.reset(0);
        return fail_text(0, err);
    }
    double t7 = asm_now();

    result.stats.lex = t1 - t0;
    result.stats.split = t2 - t1;
    result.stats.size = t3 - t2;
    result.stats.lower = t4 - t3;
    result.stats.layout = t5 - t4;
    result.stats.resolve = t6 - t5;
    result.stats.emit = t7 - t6;
    result.ok = true;
    return result;
}

// ------------------------------------------------------------- front door

inline unsigned c16_default_threads() {
    return asm_default_threads();
}

inline void c16_backend_from_env(c16_options& opt, size_t input_bytes) {
    const char* threads = std::getenv("C16_THREADS");
    opt.threads = c16_default_threads();
    if (threads != nullptr) {
        int n = std::atoi(threads);
        if (n > 0) {
            opt.threads = static_cast<unsigned>(n);
        }
    }
    const char* backend = std::getenv("C16_BACKEND");
    std::string_view name = backend != nullptr ? backend : "auto";
    if (name == "serial") {
        opt.backend = c16_backend::serial;
    }
    else if (name == "threads") {
        opt.backend = c16_backend::threads;
    }
    else if (name == "hip") {
        opt.backend = c16_backend::hip;
    }
    else {
        // Same break even as the assembler's, and for the same reason:
        // below a couple of megabytes of source, starting the threads costs
        // more than the work they take away.  Real cpu16 programs are a few
        // hundred bytes, so in practice this means "serial".
        opt.backend = input_bytes >= (2u << 20) ? c16_backend::threads : c16_backend::serial;
    }
}

#endif  // C16_PIPELINE_HPP
