// A benchmark for the c16 compiler's parallel stages, and the test that its
// two output paths agree.
//
//   c16_bench [--functions N] [--body M] [--seed S] [--repeat R]
//             [--threads N] [--check]
//
// It generates a synthetic program of the requested size, compiles it once
// per path per backend, checks that
//
//   * every backend of a path produced byte for byte the same output, and
//   * assembling the text path's assembly with this repository's own asm16
//     produces exactly the machine words the binary path produced,
//
// and prints throughput and speedup.  --check is the same thing with the
// printing turned into a pass/fail line, which is what CTest runs.
//
// One honest caveat, the same one asm_bench carries: cpu16 has 256
// instruction words and 96 bytes of frame space, and a program that small is
// far too small to measure anything.  The benchmark therefore lifts exactly
// those two limits through c16_options::relaxed_limits.  Every other byte of
// the work - lexing, splitting, sizing, lowering, layout, resolution,
// emission - is exactly what the real compiler does.

#include "c16_pipeline.hpp"

#include <cinttypes>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

// xorshift64*, so that the generated program does not depend on the host's
// random number library.
struct rng {
    uint64_t state;
    explicit rng(uint64_t seed) : state(seed == 0 ? 0x9e3779b97f4a7c15ull : seed) {}
    uint64_t next() {
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        return state * 0x2545f4914f6cdd1dull;
    }
    uint32_t below(uint32_t n) { return static_cast<uint32_t>(next() % n); }
};

// Build a program that looks like something a person would write: globals,
// functions with parameters and locals, arithmetic, comparisons, if/else,
// while loops, calls, comments and blank lines.
//
// The call graph is a chain - f0 calls f1 calls f2 - because it has to be
// acyclic, and because a chain gives every function the same amount of work,
// which keeps the measurement about the compiler rather than about load
// balancing.
std::vector<char> generate(size_t functions, size_t body, uint64_t seed) {
    rng r(seed);
    std::string text;
    text.reserve(functions * body * 24 + 256);
    text += "// A synthetic c16 program, generated by c16_bench.\n";
    text += "int limit = 200;\n";
    text += "int seed = 7;\n\n";

    const char* const binop[] = {"+", "-", "*", "&", "|", "^"};
    const char* const relop[] = {"<", ">", "<=", ">=", "==", "!="};

    for (size_t f = 0; f < functions; f++) {
        text += "// function ";
        text += std::to_string(f);
        text += "\nint f";
        text += std::to_string(f);
        text += "(int a, int b) {\n";
        text += "    int x = a + b;\n";
        text += "    int y = limit - a;\n";
        for (size_t s = 0; s < body; s++) {
            uint32_t roll = r.below(100);
            const char* op = binop[r.below(6)];
            const char* rel = relop[r.below(6)];
            const char* lhs = r.below(2) == 0 ? "x" : "y";
            const char* rhs = r.below(2) == 0 ? "a" : "b";
            if (roll < 8) {
                text += "    // a comment the lexer has to strip\n";
                continue;
            }
            if (roll < 12) {
                text += "\n";
                continue;
            }
            if (roll < 24) {
                text += "    if (";
                text += lhs;
                text += " ";
                text += rel;
                text += " ";
                text += rhs;
                text += ") { x = x ";
                text += op;
                text += " 1; } else { y = y + seed; }\n";
                continue;
            }
            if (roll < 32) {
                text += "    while (y ";
                text += r.below(2) == 0 ? ">" : "<";
                text += " ";
                text += rhs;
                text += ") { y = y - 1; x = x + 1; }\n";
                continue;
            }
            if (roll < 40) {
                text += "    int t";
                text += std::to_string(s);
                text += " = (";
                text += lhs;
                text += " ";
                text += op;
                text += " ";
                text += rhs;
                text += ") ";
                text += op;
                text += " (x + ";
                text += std::to_string(1 + r.below(30));
                text += ");\n";
                continue;
            }
            if (roll < 46) {
                text += "    poke(";
                text += std::to_string(r.below(60));
                text += ", ";
                text += lhs;
                text += ");\n";
                continue;
            }
            if (roll < 52) {
                text += "    x = peek(";
                text += std::to_string(r.below(60));
                text += ") ";
                text += op;
                text += " y;\n";
                continue;
            }
            text += "    ";
            text += lhs;
            text += " = ";
            text += lhs;
            text += " ";
            text += op;
            text += " ";
            text += rhs;
            if (r.below(3) == 0) {
                text += " ";
                text += binop[r.below(6)];
                text += " ";
                text += std::to_string(r.below(50));
            }
            text += ";";
            if (r.below(4) == 0) {
                text += "   // trailing comment";
            }
            text += "\n";
        }
        if (f + 1 < functions) {
            text += "    return x + f";
            text += std::to_string(f + 1);
            text += "(a, y);\n}\n\n";
        }
        else {
            text += "    return x + y;\n}\n\n";
        }
    }
    text += "int main() {\n    out(0, f0(1, 2));\n    return 0;\n}\n";
    return std::vector<char>(text.begin(), text.end());
}

// A whole small program of the size cpu16 can actually run.  Nothing here
// lifts any limit: every unit this produces fits inside the real 256
// instruction words and the real 96 bytes of frame space, which is the
// entire point of measuring this way.
std::vector<char> generate_unit(rng& r, size_t index) {
    const char* const binop[] = {"+", "-", "*", "&", "|", "^"};
    const char* const relop[] = {"<", ">", "<=", ">=", "==", "!="};
    std::string t;
    t += "// unit ";
    t += std::to_string(index);
    t += ", one program for a machine with 256 instruction words\n";
    t += "int base = ";
    t += std::to_string(1 + r.below(60));
    t += ";\n\nint step(int v) {\n    int s = v ";
    t += binop[r.below(6)];
    t += " base;\n    if (s ";
    t += relop[r.below(6)];
    t += " ";
    t += std::to_string(1 + r.below(90));
    t += ") { s = s - 1; } else { s = s + 2; }\n    return s;\n}\n\n";
    t += "int main() {\n    int x = ";
    t += std::to_string(r.below(40));
    t += ";\n    int i = 0;\n    while (i < ";
    t += std::to_string(3 + r.below(12));
    t += ") {\n        x = step(x);\n";
    if (r.below(2) == 0) {
        t += "        if (x & 1) { x = x + 3; }\n";
    }
    t += "        i = i + 1;\n    }\n";
    t += "    out(0, x);\n    out(1, x ";
    t += binop[r.below(6)];
    t += " base);\n    return 0;\n}\n";
    return std::vector<char>(t.begin(), t.end());
}

std::vector<c16_unit> generate_units(size_t count, uint64_t seed) {
    rng r(seed);
    std::vector<c16_unit> units(count);
    for (size_t i = 0; i < count; i++) {
        units[i].name = "unit" + std::to_string(i) + ".c16";
        units[i].source = generate_unit(r, i);
    }
    return units;
}

struct measurement {
    bool ran = false;
    std::string note;
    double seconds = 0;
    c16_stats stats;
    asm_array<uint8_t> output;
};

measurement run(const std::vector<char>& source, c16_backend backend, unsigned threads,
                bool text, int repeat) {
    measurement m;
    c16_options opt;
    opt.backend = backend;
    opt.threads = threads;
    opt.text = text;
    opt.hex = true;
    opt.sep_with_line = true;
    opt.relaxed_limits = true;
    for (int i = 0; i < repeat; i++) {
        double t0 = asm_now();
        c16_result result = c16_compile(source, opt);
        double t1 = asm_now();
        if (!result.ok) {
            m.note = result.error.line != 0
                     ? std::format("line {}: {}", result.error.line, result.error.message)
                     : result.error.message;
            return m;
        }
        if (!m.ran || t1 - t0 < m.seconds) {
            m.seconds = t1 - t0;
            m.stats = result.stats;
        }
        m.ran = true;
        if (m.output.size() == 0) {
            m.output = std::move(result.output);
        }
    }
    return m;
}

bool same(const measurement& a, const measurement& b) {
    if (!a.ran || !b.ran) {
        return true;   // nothing to compare against
    }
    return a.output.size() == b.output.size() &&
           std::memcmp(a.output.data(), b.output.data(), a.output.size()) == 0;
}

// The cross path check: run the text path's output through this repository's
// own assembler and see whether the words come out the same as the ones the
// binary path produced without ever writing any text.
bool assembles_to(const measurement& text, const measurement& binary, std::string* why) {
    if (!text.ran || !binary.ran) {
        return true;
    }
    std::vector<char> source(reinterpret_cast<const char*>(text.output.data()),
                             reinterpret_cast<const char*>(text.output.data()) +
                             text.output.size());
    asm_options opt;
    opt.hex = true;
    opt.sep_with_line = true;
    opt.address_limit = 0xffffffffu;
    asm_result assembled = asm_assemble<asm_cpu16>(source, opt);
    if (!assembled.ok) {
        *why = "asm16 rejected the compiler's assembly: " +
               asm_error_text<asm_cpu16>(assembled.error);
        return false;
    }
    if (assembled.output.size() != binary.output.size()) {
        *why = std::format("the text path assembles to {} bytes, the binary path emitted {}",
                           assembled.output.size(), binary.output.size());
        return false;
    }
    if (std::memcmp(assembled.output.data(), binary.output.data(),
                    assembled.output.size()) != 0) {
        *why = "the two paths produced different machine words";
        return false;
    }
    return true;
}

struct project_measurement {
    bool ran = false;
    std::string note;
    double seconds = 0;
    c16_project_stats stats;
    std::vector<std::vector<uint8_t>> outputs;
};

project_measurement run_project(const std::vector<c16_unit>& units, c16_backend backend,
                                unsigned threads, bool text, int repeat) {
    project_measurement m;
    c16_options opt;
    opt.backend = backend;
    opt.threads = threads;
    opt.text = text;
    opt.hex = true;
    opt.sep_with_line = true;
    opt.relaxed_limits = false;   // these programs really do fit on the hardware
    for (int i = 0; i < repeat; i++) {
        double t0 = asm_now();
        c16_project_result r = c16_compile_all(units, opt);
        double t1 = asm_now();
        if (!r.ok) {
            const c16_error& e = r.units[r.first_failure].error;
            m.note = units[r.first_failure].name + ": " + e.message;
            return m;
        }
        if (!m.ran || t1 - t0 < m.seconds) {
            m.seconds = t1 - t0;
            m.stats = r.stats;
        }
        m.ran = true;
        if (m.outputs.empty()) {
            m.outputs.resize(units.size());
            for (size_t u = 0; u < units.size(); u++) {
                const asm_array<uint8_t>& o = r.units[u].output;
                m.outputs[u].assign(o.data(), o.data() + o.size());
            }
        }
    }
    return m;
}

bool same_project(const project_measurement& a, const project_measurement& b) {
    if (!a.ran || !b.ran) {
        return true;
    }
    return a.outputs == b.outputs;
}

// Same cross path question as for one file: does the assembly the text path
// wrote assemble, unit by unit, to exactly the words the binary path emitted?
bool project_paths_agree(const project_measurement& text, const project_measurement& binary,
                         const std::vector<c16_unit>& units, std::string* why) {
    if (!text.ran || !binary.ran) {
        return true;
    }
    asm_options opt;
    opt.hex = true;
    opt.sep_with_line = true;
    for (size_t i = 0; i < units.size(); i++) {
        std::vector<char> src(text.outputs[i].begin(), text.outputs[i].end());
        asm_result r = asm_assemble<asm_cpu16>(src, opt);
        if (!r.ok) {
            *why = units[i].name + ": asm16 rejected the compiler's assembly: " +
                   asm_error_text<asm_cpu16>(r.error);
            return false;
        }
        if (r.output.size() != binary.outputs[i].size() ||
            std::memcmp(r.output.data(), binary.outputs[i].data(), r.output.size()) != 0) {
            *why = units[i].name + ": the two paths produced different machine words";
            return false;
        }
    }
    return true;
}

void print_project_row(const char* name, const project_measurement& m, double serial_seconds,
                       size_t files, size_t input_bytes, size_t lines) {
    if (!m.ran) {
        std::printf("    %-10s unavailable: %s\n", name, m.note.c_str());
        return;
    }
    std::printf("    %-10s %9.2f ms %10.0f file/s %10.3f Mline/s %8.1f MB/s %7.2fx\n",
                name, m.seconds * 1e3, static_cast<double>(files) / m.seconds,
                static_cast<double>(lines) / m.seconds / 1e6,
                static_cast<double>(input_bytes) / (1024.0 * 1024.0) / m.seconds,
                serial_seconds > 0 ? serial_seconds / m.seconds : 0.0);
}

// The measurement the single file benchmark cannot make.  Separate programs
// share nothing, so this is the one place in the compiler with no serial
// section at all, and it is also the only shape that matches what cpu16 can
// really run.
int project(size_t files, uint64_t seed, int repeat, unsigned threads, bool check_only) {
    std::vector<c16_unit> units = generate_units(files, seed);
    size_t input_bytes = 0;
    for (const c16_unit& u : units) {
        input_bytes += u.source.size();
    }

    project_measurement ts = run_project(units, c16_backend::serial, 1, true, repeat);
    if (!ts.ran) {
        std::fprintf(stderr, "TEST FAIL: the serial text path failed: %s\n", ts.note.c_str());
        return 1;
    }
    project_measurement tt = run_project(units, c16_backend::threads, threads, true, repeat);
    project_measurement bs = run_project(units, c16_backend::serial, 1, false, repeat);
    if (!bs.ran) {
        std::fprintf(stderr, "TEST FAIL: the serial binary path failed: %s\n", bs.note.c_str());
        return 1;
    }
    project_measurement bt = run_project(units, c16_backend::threads, threads, false, repeat);
    project_measurement th;
    project_measurement bh;
    if (c16_hip_available()) {
        th = run_project(units, c16_backend::hip, threads, true, repeat);
        bh = run_project(units, c16_backend::hip, threads, false, repeat);
    }
    else {
        th.note = "no HIP device";
        bh.note = "no HIP device";
    }

    std::string why;
    bool identical = same_project(ts, tt) && same_project(ts, th) &&
                     same_project(bs, bt) && same_project(bs, bh);
    bool agree = project_paths_agree(ts, bs, units, &why);

    if (check_only) {
        std::printf("c16: %zu separate programs, %zu lines, %zu instruction words, "
                    "all within the real cpu16 limits\n",
                    ts.stats.units, ts.stats.lines, ts.stats.words);
        if (!identical) {
            std::printf("TEST FAIL: the backends disagree about the bytes of some unit\n");
            return 1;
        }
        if (!agree) {
            std::printf("TEST FAIL: %s\n", why.c_str());
            return 1;
        }
        std::printf("TEST PASS: %zu programs, every backend agreed, and every text path "
                    "output assembles to exactly its binary path words\n", files);
        return 0;
    }

    std::printf("\nc16 across separate files: %zu programs, %zu source lines, %.2f MiB, "
                "%zu instruction words\n",
                ts.stats.units, ts.stats.lines,
                static_cast<double>(input_bytes) / (1024.0 * 1024.0), ts.stats.words);
    std::printf("every program fits the real cpu16: 256 instruction words, 96 bytes of "
                "frames, no limits lifted\n");
    std::printf("best of %d run(s); seed %" PRIu64 "; %u threads; gpu: %s\n\n", repeat, seed,
                threads, c16_hip_available() ? c16_hip_device_name().c_str() : "none detected");

    std::printf("  text path\n");
    print_project_row("serial", ts, ts.seconds, files, input_bytes, ts.stats.lines);
    print_project_row("threads", tt, ts.seconds, files, input_bytes, ts.stats.lines);
    print_project_row("hip", th, ts.seconds, files, input_bytes, ts.stats.lines);
    std::printf("  binary path\n");
    print_project_row("serial", bs, bs.seconds, files, input_bytes, bs.stats.lines);
    print_project_row("threads", bt, bs.seconds, files, input_bytes, bs.stats.lines);
    print_project_row("hip", bh, bs.seconds, files, input_bytes, bs.stats.lines);

    if (tt.ran) {
        std::printf("\n  parallel efficiency across files: %.0f%% of %u threads (text), ",
                    100.0 * (ts.seconds / tt.seconds) / threads, threads);
        std::printf("%.0f%% (binary)\n",
                    100.0 * (bs.seconds / bt.seconds) / threads);
    }
    std::printf("  identical bytes across the backends: %s\n", identical ? "yes" : "NO");
    std::printf("  every text path output assembles to its binary path words: %s\n",
                agree ? "yes" : ("NO - " + why).c_str());
    return identical && agree ? 0 : 1;
}

// The text path is not finished when the compiler stops: something still has
// to turn that assembly into machine words.  This times that second half with
// this repository's own asm16, so the report can compare the whole round trip
// against the binary path rather than only the first half of it.
double reassemble_seconds(const measurement& text, unsigned threads, bool parallel,
                          int repeat) {
    if (!text.ran) {
        return 0;
    }
    std::vector<char> source(reinterpret_cast<const char*>(text.output.data()),
                             reinterpret_cast<const char*>(text.output.data()) +
                             text.output.size());
    asm_options opt;
    opt.hex = true;
    opt.sep_with_line = true;
    opt.address_limit = 0xffffffffu;
    opt.backend = parallel ? asm_backend::threads : asm_backend::serial;
    opt.threads = parallel ? threads : 1;
    double best = 0;
    for (int i = 0; i < repeat; i++) {
        double t0 = asm_now();
        asm_result r = asm_assemble<asm_cpu16>(source, opt);
        double t1 = asm_now();
        if (!r.ok) {
            return 0;
        }
        if (best == 0 || t1 - t0 < best) {
            best = t1 - t0;
        }
    }
    return best;
}

void print_row(const char* name, const measurement& m, double serial_seconds,
               size_t input_bytes, size_t lines) {
    if (!m.ran) {
        std::printf("    %-10s %-60s\n", name, ("unavailable: " + m.note).c_str());
        return;
    }
    double mb = static_cast<double>(input_bytes) / (1024.0 * 1024.0);
    std::printf("    %-10s %9.2f ms %11.3f Mline/s %9.1f MB/s %7.2fx  %s\n",
                name, m.seconds * 1e3,
                static_cast<double>(lines) / m.seconds / 1e6,
                mb / m.seconds,
                serial_seconds > 0 ? serial_seconds / m.seconds : 0.0,
                m.stats.threads > 1 ? (std::to_string(m.stats.threads) + " threads").c_str()
                                    : "");
}

void print_stages(const char* name, const measurement& m) {
    if (!m.ran) {
        return;
    }
    std::printf("    %-10s lex %7.2f  split %7.2f  size %6.2f  lower %8.2f  "
                "layout %6.2f  resolve %5.2f  emit %7.2f   (ms)\n",
                name, m.stats.lex * 1e3, m.stats.split * 1e3, m.stats.size * 1e3,
                m.stats.lower * 1e3, m.stats.layout * 1e3, m.stats.resolve * 1e3,
                m.stats.emit * 1e3);
}

// Threads are not free: below some size the fork and join costs more than the
// work.  This finds that size by doubling until the parallel backend wins.
int sweep(size_t body, uint64_t seed, int repeat, unsigned threads) {
    std::printf("\nbreak even sweep, %u threads, best of %d\n", threads, repeat);
    std::printf("  %10s %10s %12s %12s %9s %12s %12s %9s\n",
                "functions", "source", "text serial", "text thr", "speedup",
                "bin serial", "bin thr", "speedup");
    for (size_t f = 1; f <= 40000; f *= 2) {
        std::vector<char> source = generate(f, body, seed);
        measurement ts = run(source, c16_backend::serial, 1, true, repeat);
        measurement tt = run(source, c16_backend::threads, threads, true, repeat);
        measurement bs = run(source, c16_backend::serial, 1, false, repeat);
        measurement bt = run(source, c16_backend::threads, threads, false, repeat);
        if (!ts.ran || !tt.ran || !bs.ran || !bt.ran) {
            std::fprintf(stderr, "TEST FAIL: sweep failed at %zu functions\n", f);
            return 1;
        }
        char size[32];
        std::snprintf(size, sizeof(size), "%.2f MiB",
                      static_cast<double>(source.size()) / (1024.0 * 1024.0));
        std::printf("  %10zu %10s %9.3f ms %9.3f ms %8.2fx %9.3f ms %9.3f ms %8.2fx\n",
                    f, size, ts.seconds * 1e3, tt.seconds * 1e3, ts.seconds / tt.seconds,
                    bs.seconds * 1e3, bt.seconds * 1e3, bs.seconds / bt.seconds);
    }
    return 0;
}

// Where compiling files concurrently starts to pay.
int file_sweep(uint64_t seed, int repeat, unsigned threads) {
    std::printf("\nbreak even across files, %u threads, best of %d\n", threads, repeat);
    std::printf("  %8s %10s %13s %13s %9s\n", "files", "source", "serial", "threads",
                "speedup");
    for (size_t f = 1; f <= 65536; f *= 4) {
        std::vector<c16_unit> units = generate_units(f, seed);
        size_t bytes = 0;
        for (const c16_unit& u : units) {
            bytes += u.source.size();
        }
        project_measurement bs = run_project(units, c16_backend::serial, 1, false, repeat);
        project_measurement bt = run_project(units, c16_backend::threads, threads, false,
                                             repeat);
        if (!bs.ran || !bt.ran) {
            std::fprintf(stderr, "TEST FAIL: file sweep failed at %zu files\n", f);
            return 1;
        }
        char size[32];
        std::snprintf(size, sizeof(size), "%.3f MiB",
                      static_cast<double>(bytes) / (1024.0 * 1024.0));
        std::printf("  %8zu %10s %10.3f ms %10.3f ms %8.2fx\n", f, size,
                    bs.seconds * 1e3, bt.seconds * 1e3, bs.seconds / bt.seconds);
    }
    return 0;
}

int bench(size_t functions, size_t body, uint64_t seed, int repeat, unsigned threads,
          bool check_only) {
    std::vector<char> source = generate(functions, body, seed);

    measurement text_serial = run(source, c16_backend::serial, 1, true, repeat);
    if (!text_serial.ran) {
        std::fprintf(stderr, "TEST FAIL: the serial text path failed: %s\n",
                     text_serial.note.c_str());
        return 1;
    }
    measurement text_threads = run(source, c16_backend::threads, threads, true, repeat);
    measurement text_hip;
    measurement binary_serial = run(source, c16_backend::serial, 1, false, repeat);
    if (!binary_serial.ran) {
        std::fprintf(stderr, "TEST FAIL: the serial binary path failed: %s\n",
                     binary_serial.note.c_str());
        return 1;
    }
    measurement binary_threads = run(source, c16_backend::threads, threads, false, repeat);
    measurement binary_hip;
    if (c16_hip_available()) {
        text_hip = run(source, c16_backend::hip, threads, true, repeat);
        binary_hip = run(source, c16_backend::hip, threads, false, repeat);
    }
    else {
        text_hip.note = "no HIP device";
        binary_hip.note = "no HIP device";
    }

    std::string why;
    bool identical = same(text_serial, text_threads) && same(text_serial, text_hip) &&
                     same(binary_serial, binary_threads) && same(binary_serial, binary_hip);
    bool paths_agree = assembles_to(text_serial, binary_serial, &why);

    if (check_only) {
        std::printf("c16: %zu functions, %zu lines, %zu items, %zu instruction words\n",
                    text_serial.stats.functions, text_serial.stats.lines,
                    text_serial.stats.items, text_serial.stats.words);
        std::printf("  text   backends: serial ok, threads %s, hip %s\n",
                    text_threads.ran ? "ok" : text_threads.note.c_str(),
                    text_hip.ran ? "ok" : text_hip.note.c_str());
        std::printf("  binary backends: serial ok, threads %s, hip %s\n",
                    binary_threads.ran ? "ok" : binary_threads.note.c_str(),
                    binary_hip.ran ? "ok" : binary_hip.note.c_str());
        if (!identical) {
            std::printf("TEST FAIL: the backends of one path disagree about their bytes\n");
            return 1;
        }
        if (!paths_agree) {
            std::printf("TEST FAIL: %s\n", why.c_str());
            return 1;
        }
        std::printf("TEST PASS: every backend agreed, and the text path assembles to "
                    "exactly the binary path's %zu bytes\n", binary_serial.output.size());
        return 0;
    }

    double mb = static_cast<double>(source.size()) / (1024.0 * 1024.0);
    std::printf("\nc16 compiler: %zu functions, %zu source lines, %.2f MiB, "
                "%zu lowered items, %zu instruction words\n",
                text_serial.stats.functions, text_serial.stats.lines, mb,
                text_serial.stats.items, text_serial.stats.words);
    std::printf("best of %d run(s); seed %" PRIu64 "; gpu: %s\n", repeat, seed,
                c16_hip_available() ? c16_hip_device_name().c_str() : "none detected");
    std::printf("text path output %zu bytes, binary path output %zu bytes\n\n",
                text_serial.output.size(), binary_serial.output.size());

    std::printf("  %-10s %9s %14s %14s %8s\n", "backend", "time", "throughput", "", "speedup");
    std::printf("  text path (cpu16 assembly, re-assembled by asm16 afterwards)\n");
    print_row("serial", text_serial, text_serial.seconds, source.size(), text_serial.stats.lines);
    print_row("threads", text_threads, text_serial.seconds, source.size(), text_serial.stats.lines);
    print_row("hip", text_hip, text_serial.seconds, source.size(), text_serial.stats.lines);
    std::printf("  binary path (machine words straight out of the compiler)\n");
    print_row("serial", binary_serial, binary_serial.seconds, source.size(),
              binary_serial.stats.lines);
    print_row("threads", binary_threads, binary_serial.seconds, source.size(),
              binary_serial.stats.lines);
    print_row("hip", binary_hip, binary_serial.seconds, source.size(), binary_serial.stats.lines);

    std::printf("\n  where the time goes:\n");
    std::printf("  text path\n");
    print_stages("serial", text_serial);
    print_stages("threads", text_threads);
    print_stages("hip", text_hip);
    std::printf("  binary path\n");
    print_stages("serial", binary_serial);
    print_stages("threads", binary_threads);
    print_stages("hip", binary_hip);

    std::printf("\n  the whole job, text path against binary path.  The text path is only\n"
                "  half done when the compiler stops - asm16 still has to read that\n"
                "  assembly back and encode it - so this adds that second half in:\n");
    double reasm_serial = reassemble_seconds(text_serial, threads, false, repeat);
    double reasm_threads = reassemble_seconds(text_threads, threads, true, repeat);
    if (reasm_serial > 0) {
        double total = text_serial.seconds + reasm_serial;
        std::printf("    serial   c16 %6.2f + asm16 %6.2f = %7.2f ms   vs binary %6.2f ms   %5.2fx\n",
                    text_serial.seconds * 1e3, reasm_serial * 1e3, total * 1e3,
                    binary_serial.seconds * 1e3, total / binary_serial.seconds);
    }
    if (reasm_threads > 0 && binary_threads.ran) {
        double total = text_threads.seconds + reasm_threads;
        std::printf("    threads  c16 %6.2f + asm16 %6.2f = %7.2f ms   vs binary %6.2f ms   %5.2fx\n",
                    text_threads.seconds * 1e3, reasm_threads * 1e3, total * 1e3,
                    binary_threads.seconds * 1e3, total / binary_threads.seconds);
    }

    std::printf("\n  compiler only, binary path against text path, same backend:\n");
    if (text_serial.ran && binary_serial.ran) {
        std::printf("    serial   %6.2f ms vs %6.2f ms  %5.2fx\n",
                    binary_serial.seconds * 1e3, text_serial.seconds * 1e3,
                    text_serial.seconds / binary_serial.seconds);
    }
    if (text_threads.ran && binary_threads.ran) {
        std::printf("    threads  %6.2f ms vs %6.2f ms  %5.2fx\n",
                    binary_threads.seconds * 1e3, text_threads.seconds * 1e3,
                    text_threads.seconds / binary_threads.seconds);
    }
    if (text_hip.ran && binary_hip.ran) {
        std::printf("    hip      %6.2f ms vs %6.2f ms  %5.2fx\n",
                    binary_hip.seconds * 1e3, text_hip.seconds * 1e3,
                    text_hip.seconds / binary_hip.seconds);
    }

    std::printf("\n  identical bytes across the backends of a path: %s\n",
                identical ? "yes" : "NO");
    std::printf("  the text path assembles to the binary path's words: %s\n",
                paths_agree ? "yes" : ("NO - " + why).c_str());
    return identical && paths_agree ? 0 : 1;
}

}  // namespace

int main(int argc, char* argv[]) {
    size_t functions = 20000;
    size_t body = 24;
    uint64_t seed = 1;
    int repeat = 3;
    bool check_only = false;
    bool sweep_only = false;
    size_t files = 0;
    unsigned threads = c16_default_threads();

    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        auto value = [&]() -> const char* { return i + 1 < argc ? argv[++i] : "0"; };
        if (a == "--functions") {
            functions = static_cast<size_t>(std::atoll(value()));
        }
        else if (a == "--body") {
            body = static_cast<size_t>(std::atoll(value()));
        }
        else if (a == "--seed") {
            seed = static_cast<uint64_t>(std::atoll(value()));
        }
        else if (a == "--repeat") {
            repeat = std::atoi(value());
        }
        else if (a == "--threads") {
            threads = static_cast<unsigned>(std::atoi(value()));
        }
        else if (a == "--check") {
            check_only = true;
        }
        else if (a == "--sweep") {
            sweep_only = true;
        }
        else if (a == "--files") {
            files = static_cast<size_t>(std::atoll(value()));
        }
        else if (a == "--file-sweep") {
            files = SIZE_MAX;
        }
        else if (a == "--help") {
            std::printf("Usage: c16_bench [--functions N] [--body M] [--seed S]\n"
                        "                 [--repeat R] [--threads N] [--check] [--sweep]\n"
                        "                 [--files N] [--file-sweep]\n"
                        "\n--files N compiles N separate small programs, each one small\n"
                        "enough to run on the real cpu16, instead of one huge file.\n");
            return 0;
        }
        else {
            std::fprintf(stderr, "c16_bench: unknown option '%s'\n", a.c_str());
            return 2;
        }
    }
    if (functions < 1) {
        functions = 1;
    }
    if (repeat < 1) {
        repeat = 1;
    }
    if (threads < 1) {
        threads = 1;
    }
    if (files == SIZE_MAX) {
        return file_sweep(seed, repeat, threads);
    }
    if (files > 0) {
        return project(files, seed, repeat, threads, check_only);
    }
    if (sweep_only) {
        return sweep(body, seed, repeat, threads);
    }
    return bench(functions, body, seed, repeat, threads, check_only);
}
