#!/usr/bin/env python3
"""Compute the input data and the reference result for the gemm64 benchmark.

docs/gpu_isa.md section 7.1 defines `gemm64` as

    C[64][64] = A[64][64] * Bt[64][64], int8 -> int32

with `B` pre-transposed, so `C[m][n] = sum_k A[m][k] * Bt[n][k]`, and says
that the inputs are "generated by a fixed linear congruential sequence so that
every tier produces bit-identical results and a mismatch is a bug, not a
tolerance question".  This is that sequence, and the GEMM below is the
definition written out in Python.

**Nothing here is read back from the RTL.**  The reference is a plain triple
loop over the same integers the GPU is given; it shares no code, no tiling and
no accumulator layout with `tests/gemm64.s`.  A kernel that transposes a tile,
swaps two waves' output rows or drops the last k panel produces a
plausible-looking matrix, and only an independent multiply notices.

The memory image it writes is the one `tests/gemm64.s` expects:

    byte 0      the kernel argument block, section 4.12: &A, &Bt, &C, M, N, K
    byte 64     A, 64 rows of 64 int8
    byte 4160   Bt, 64 rows of 64 int8
    byte 8256   C, 64 rows of 64 int32 - written by the kernel, checked here

C is deliberately *not* in the data image.  Every one of its 4096 words is
left undefined, so a word the kernel never stores stays `x` and the
comparison fails; an image of zeros would have hidden exactly that bug.

usage:
    gen_gemm64.py <tests-dir>

It rewrites tests/gemm64.data32 and tests/gemm64.mexpect in place, and is run
by the `gpu_gemm64_data` CTest, which fails if the checked-in files are not
what it produces.
"""

import os
import sys

M = 64
N = 64
K = 64

ARGS_ADDR = 0
A_ADDR = 64
BT_ADDR = A_ADDR + M * K
C_ADDR = BT_ADDR + N * K


def lcg_bytes(count, seed):
    """The fixed sequence of section 7.1, as signed 8-bit values.

    Knuth's constants, and the byte taken from bits 16..23 because the low
    bits of a power-of-two-modulus LCG have short periods - bit 0 alternates,
    and a matrix of alternating operands would hide an A fragment read from
    the wrong lane.
    """
    out = []
    x = seed
    for _ in range(count):
        x = (1103515245 * x + 12345) & 0x7FFFFFFF
        b = (x >> 16) & 0xFF
        out.append(b - 256 if b >= 128 else b)
    return out


def pack(values):
    """Four signed bytes per 32-bit word, little-endian."""
    words = []
    for i in range(0, len(values), 4):
        w = 0
        for j in range(4):
            w |= (values[i + j] & 0xFF) << (8 * j)
        words.append(w)
    return words


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: gen_gemm64.py <tests-dir>\n")
        return 2
    out_dir = sys.argv[1]

    a = lcg_bytes(M * K, 20260918)
    bt = lcg_bytes(N * K, 987654321)

    # C[m][n] = sum_k A[m][k] * Bt[n][k], int32.  int8 inputs and K = 64
    # cannot overflow int32, so no masking is needed to be faithful.
    c = []
    for m in range(M):
        row_a = a[m * K:(m + 1) * K]
        for n in range(N):
            row_b = bt[n * K:(n + 1) * K]
            c.append(sum(row_a[k] * row_b[k] for k in range(K)))

    words = [0] * (C_ADDR // 4)
    words[0] = A_ADDR
    words[1] = BT_ADDR
    words[2] = C_ADDR
    words[3] = M
    words[4] = N
    words[5] = K
    words[A_ADDR // 4:A_ADDR // 4 + M * K // 4] = pack(a)
    words[BT_ADDR // 4:BT_ADDR // 4 + N * K // 4] = pack(bt)

    with open(os.path.join(out_dir, "gemm64.data32"), "w") as f:
        f.write("// gemm64's global memory image, generated by "
                "tests/gen_gemm64.py.\n")
        f.write("// Argument block, then A, then Bt; C is left undefined so "
                "that a word\n// the kernel fails to store shows up as x "
                "rather than as a zero.\n")
        for w in words:
            f.write("%08x\n" % (w & 0xFFFFFFFF))

    with open(os.path.join(out_dir, "gemm64.mexpect"), "w") as f:
        f.write("// gemm64's C matrix, 64 rows of 64 int32, computed by "
                "tests/gen_gemm64.py\n// from section 7.1's definition and "
                "never read back from the RTL.\n")
        f.write("// The testbench loads this at word %d, byte %d.\n"
                % (C_ADDR // 4, C_ADDR))
        for i, v in enumerate(c):
            f.write("%08x\n" % (v & 0xFFFFFFFF))
    return 0


if __name__ == "__main__":
    sys.exit(main())
